name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag version'
        required: true
        type: string
      tag_latest:
        description: 'Tag as latest version?'
        default: true
        required: false
        type: boolean
      tag_minimal:
        default: ""
        description: 'Minimal supported tag version'
        required: false
        type: string

permissions:
  actions: write
  contents: write
  security-events: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-linux
    uses: carlspring/github-reusable-workflow/.github/workflows/publish-docker-image.yml@f4bae5e
#    secrets: inherit
    with:
      image_name: "${{ github.event.repository.name }}"
      tag: "${{ inputs.tag }}"
      tag_latest: "${{ inputs.tag_latest }}"
      tag_minimal: "${{ inputs.tag_minimal }}"
